<header class="front__header">
    <?php
    //Shortcut in index.phtml $datas = $this->>vars['options']

    if (!empty($this->vars['options']['flash-message'])) { ?>
    <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
        <?php

        foreach ($this->vars['options']['flash-message'] as $key){ ?>

            <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
        <?php }
        ?>
    </div>
    <?php } ?>

    <!-- <img src="<?= $datas['header']['banner']['data'][0]['url'] ?>" alt="<?= $datas['header']['banner']['content'] .
        '-' .  $datas['header']['site_sub_title']['content'] .
        '-' . $datas['header']['site_title']['content']  ?> ">
        -->
    <?php
    // explode main title and insert each chunk in span tag
    $explode = \explode(' ', $datas['header']['site_title']['content']);
    $lastValue = end($explode);
    $mainTitle = '';
    foreach ($explode as $key => $value) {
        if ($value !== $lastValue){
            $mainTitle .= '<span class="front__header_chunkTitle">' . $value . '</span>' . ' ';

        }
        else {
            $mainTitle .= '<span class="front__header_chunkTitle">' . $value . '</span>';

        }
    }
    ?>

    <h1><?= $mainTitle ?></h1>
    <h2><?= $datas['header']['site_sub_title']['content'] ?></h2>

    <?php if (!empty($_SESSION)){ ?>
        <div class="front__link_BO">
            <a href="/admin/">Back-Office</a>

        </div>
    <?php } ?>



    <?php include("block__navigation_front.phtml") ?>
</header>


