<!DOCTYPE html>
<html lang="fr">
<?php
// Shortcut


$datas = $this->vars['options'];
include("block__head_front.phtml");

if (!empty($datas)) {
?>
<body class="front__main_content">
<?php include("block__header_front.phtml"); ?>

<?php

// Contenu Homepage Front
$section1 = $datas['main']['section_1']['data'];

?>
<main class="front__main_wrapper front__project_list">
    <h2>Les projets sur lesquels j'ai travaillé</h2>
    <section class="flex">
        <?php foreach ($section1 as $key => $value) { ?>
            <article class="front__project_list_card" style="background-image: url(<?= $value['img_url'] ?>);"> <!-- style="background-image: url(<?php //echo $value['img_url'] ?>);" -->

                <a class="front__project_list_card_title_link" href="/front/index/singleProject?id=<?= $value['id'] ?>"><h3><?= $value['name'] ?></h3></a>

                <div class="front__project_list_card_data">
                    <p class="front__project_list_card_description"><?=
                        strlen($value['short_description']) > 100 ?
                            substr($value['short_description'] , 0, 100) . '...' : $value['short_description'] ;
                        ?></p>

                    <div class="link_wrapper">
                        <a class="project__btn_to_website" href="<?= $value['website_url'] ?>" title="Vers <?= $value['name'] ?>" target="_blank">Voir le
                            site</a>
                        <a href="/single-project?id=<?= $value['id'] ?>" title="Plus de détails sur ce projet">Plus de détails</a>
                    </div>
                </div>

            </article>
        <?php } ?>
    </section>
</main>
<?php include("block__footer_front.phtml") ?>

<?php } else { ?>
    <h1>Merci de suivre la procédure d'installation avant d'aller plus loin....</h1>
<?php } ?>
<script src="../../../public/bundle.js"></script>
</body>
</html>
