<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
</head>
<body>
MAIN LAYOUT
    <header>
        ici le header
        <?php include('header.phtml') ?>
    </header>
    <section>
        ici le content
        <?php //include('content.phtml') ?>

    </section>
    <footer>
        ici le footer
        <?php include('footer.phtml') ?>

    </footer>
</body>
</html>