<!DOCTYPE html>
<html lang="fr">
    <?php include("block__admin_head.phtml"); ?>

    <body>
    <?php
    if (!empty($this->vars['options']['flash-message'])) { ?>
        <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
            <?php
            foreach ($this->vars['options']['flash-message'] as $key){ ?>
                <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
            <?php }
            ?>
        </div>
    <?php } ?>
        <header>
            <h1>Admin login</h1>
        </header>
        <main>
            <form class="admin-form" action="/login-check" method="post">
                <div>
                    <label for="login">Login</label>
                    <input id="login" name="login" type="text"/>
                </div>
                <div>
                    <label for="password">Mot de passe</label>
                    <input id="password" name="password" type="password"/>
                </div>
                <button type="submit">Se connecter</button>
            </form>
        </main>
    </body>
</html>
