<section>
    <?php
    if (!empty($this->vars['options']['flash-message'])) { ?>
        <div class="<?= $this->vars['type-class'] ?>">
            <p><?= $this->vars['options']['flash-message'] ?></p>
        </div>
    <?php } ?>

    <h1>Admin login</h1>
    <form action="/admin/login/check" method="post">
        <div>
            <label for="pseudo">Login</label>
            <input id="pseudo" type="text"/>
        </div>
        <div>
            <label for="password">Mot de passe</label>
            <input id="password" type="password"/>
        </div>
        <button type="submit">Se connecter</button>
    </form>
</section>