<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Portfolio</title>
        <link rel="stylesheet" href="/public/main.css">
        <link rel="icon" href="/public/favicon/favicon.ico">

    </head>
    <body>
        <header class="admin-header">
        <?php
        if (!empty($this->vars['options']['flash-message'])) { ?>
            <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
                <p><?= $this->vars['options']['flash-message']['message'] ?></p>
            </div>
        <?php } ?>
            <div class="header-content">
                <div class="header-welcome">
                    <h1>Admin Home</h1>
                    <p>Bienvenue dans le Back Office !!</p>
                </div>

                <div class="adminLogout">
                    <a href="/admin/login/logout" title="logout">DECONNEXION</a>
                    <a href="/" title="logout">Aller au sur le Front</a>
                </div>
            </div>
        </header>
        <main class="admin-wrapper flex">
            <aside class="admin-sidebar">
                <div>
                    <h2>Menu</h2>
                    <a href="/admin/formBuilder/index">Ajouter un nouveau types de contenu</a>
                    <ul>
                        <?php
                        foreach ($this->vars['options']['navigation'] as $key => $value){?>
                            <li>
                                <a href="/admin/content/index?name=<?= $value['contentTechnicalName'] ?>">
                                    <?= ucfirst($value['contentDisplayName']) ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div>
                    <h2>API</h2>
                    <ul>
                        <li>
                            <a href="/admin/apiDoc">Documentation API</a>
                        </li>
                    </ul>
                </div>

            </aside>
            <section class="admin-content">
                    <h2>Vue d'ensemble</h2>

                    <div class="widget-admin">
                        <h3>Listes des projets</h3>
                    </div>
                    <div class="widget-admin">
                        <h3>Liste des technos</h3>
                    </div>
                    <div class="widget-admin">
                        <h3>Liste des langages</h3>
                    </div>
                    <div class="widget-admin">
                        <h3>Liste des certifications</h3>
                    </div>
                    <div class="widget-admin">
                        <h3>Liste des règles Opquast</h3>
                    </div>

            </section>
        </main>
        <script src="../../../public/bundle.js"></script>

    </body>
</html>
