<aside class="admin-sidebar">
    <div>
        <h3>Menu</h3>
        <a class="admin_menu__add_new_content" href="/admin/formBuilder/index"><i class="fas fa-plus-square"></i> Ajouter un nouveau types de contenu</a>
        <ul class="admin_menu__dynamic_content_label">
            <?php
            foreach ($this->vars['options']['navigation'] as $key => $item) {
            ?>
            <h3><?= ucfirst($key) ?></h3>
            <?php
            if (!empty($item)) {

                foreach ($item as $key => $value) { ?>
                <?php if ($value['contentTechnicalName'] !== 'danger_zone') { ?>
                    <li>
                        <a href="/admin/content/index?content_name=<?= $value['contentTechnicalName'] ?>&id=<?= $value['id'] ?>">
                            <?= ucfirst($value['contentDisplayName']) ?>
                        </a>
                    </li>
                    <?php } else { ?>
                    <li>
                        <a href="/admin/settings/<?= $value['controller'] ?>">
                            <?= ucfirst($value['contentDisplayName']) ?>
                        </a>
                    </li>

            <?php       }
                    }
                }
            } ?>
        </ul>
    </div>
</aside>
