<header class="admin-header">
    <?php
    if (!empty($this->vars['options']['flash-message'])) { ?>
        <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
            <?php
            foreach ($this->vars['options']['flash-message'] as $key){ ?>
                <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
            <?php }
            ?>
        </div>
    <?php } ?>
    <div class="header-content">
        <div class="header-welcome">
            <h1>- Portfolio 3WAcademy -</h1>
            <p>Administration</p>
        </div>

        <div class="adminLogout">
            <a href="/admin/admin/home" title="admin_home">Admin home</a>
            <a href="/admin/login/logout" title="logout">Deconnexion</a>
            <a href="/" title="logout">Aller au sur le Front</a>
        </div>
    </div>
</header>
