<?php
if (!empty($this->vars['options']['flash-message']) || !empty($_SESSION['flash-message'])) { ?>
    <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
        <?php
        $flashMessage = $this->vars['options']['flash-message'] ?? $_SESSION['flash-message'];
        foreach ($flashMessage as $key){ ?>
            <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
        <?php }
        ?>
    </div>
<?php } ?>
