<header class="admin__header">
    <?php
    if (!empty($this->vars['options']['flash-message'])) { ?>
        <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
            <?php
            foreach ($this->vars['options']['flash-message'] as $key){ ?>
                <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
            <?php }
            ?>
        </div>
    <?php } ?>
    <div class="header-content">
        <div class="header-welcome">
            <h1>Portfolio 3WAcademy</h1>
            <h2>Administration</h2>
        </div>

        <div class="adminLogout">
            <a href="/admin/admin/home" title="admin_home"><i class="fas fa-home"></i> Admin home</a>
            <a href="/admin/login/logout" title="logout"><i class="fas fa-power-off"></i> Deconnexion</a>
            <a href="/" title="to_front"><i class="fas fa-globe-europe"></i> Aller au sur le Front</a>
        </div>
    </div>
</header>
