<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="/public/main.css">
</head>
<body>
<header class="admin-header">
    <?php
    if (!empty($this->vars['options']['flash-message'])) { ?>
        <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
            <p><?= $this->vars['options']['flash-message']['message'] ?></p>
        </div>
    <?php } ?>
    <div class="header-content">
        <div class="header-welcome">
            <h1>FORM BUILDER</h1>
            <p>Création de formulaires</p>
        </div>

        <div class="adminLogout">
            <a href="/admin/login/logout" title="logout">DECONNEXION</a>
            <a href="/" title="logout">Aller au sur le Front</a>
        </div>
    </div>
</header>
<main class="admin-wrapper flex">
    <aside class="admin-sidebar">
        <div>
            <h2>Menu</h2>
            <a href="/admin/formBuilder/index">Ajouter un nouveau types de contenu</a>
            <ul>
                <li>
                    <a href="/admin/newProject">Ajouter un projet</a>
                </li>
                <li>
                    <a href="/admin/newTechnology">Ajouter une techno</a>
                </li>
                <li>
                    <a href="/admin/newLangage">Ajouter un Langage</a>
                </li>
                <li>
                    <a href="/admin/newCertification">Ajouter une certification</a>
                </li>
                <li>
                    <a href="/admin/newHobby">Ajouter un Hobby</a>
                </li>
                <li>
                    <a href="/admin/newOpquastRule">Ajouter une règle Opquast</a>
                </li>
                <li>
                    <a href="/admin/handleColors">Gérer les couleurs des étiquettes</a>
                </li>
            </ul>
        </div>
        <div>
            <h2>API</h2>
            <ul>
                <li>
                    <a href="/admin/apiDoc">Documentation API</a>
                </li>
            </ul>
        </div>

    </aside>
    <section class="admin-content">
        <article class="welcome-formbuilder">
            <h2>FormBuilder</h2>
            <p>Bienvenue sur le formbuilder, ici on peut créer les formulaires dont on a besoin pour la création du contenu.</p>

            <p>Choisissez le premier champs à créer</p>
        </article>

        <article>
            <form class="formbuilder <?= $this->vars['options']['form-selector'] ?? '' ?>" action="">

            </form>
        </article>


    </section>
</main>
<script src="../../../public/bundle.js"></script>

</body>
</html>