<!DOCTYPE html>
<html lang="fr">
<?php include("block__admin_head.phtml"); ?>

<body>
<?php include("block__admin_header.phtml"); ?>

<main class="admin-wrapper flex">
    <?php include("block__admin_menu.phtml"); ?>

    <section class="admin-content">
        <article class="welcome-formbuilder">
            <h2>FormBuilder</h2>
            <p>Bienvenue sur le formbuilder, ici on peut créer les formulaires dont on a besoin pour la création du contenu.</p>
        </article>
        <article>
            <form class="formbuilder <?= $this->vars['options']['form-selector'] ?? '' ?>" action="/form/validator" method="post">

            </form>
        </article>


    </section>
</main>

<script src="../../../public/bundle.js"></script>

</body>
</html>
