<!DOCTYPE html>
<html lang="fr">
    <?php include("block__admin_head.phtml"); ?>

    <body>
        <?php include("block__admin_header.phtml"); ?>

        <main class="admin-wrapper flex">
            <?php include("block__admin_menu.phtml"); ?>
            <section class="admin-content">
                <form class="admin-form" action="/admin/handleColors/handleContentData" method="post">

                    <h3>ICI LE NOM DU CONTENT</h3>
                    <div class="input-text">
                        <label for="color">Nom de la techno</label><!--
                        --><input name="color" type="text" value="<?= (!empty($this->vars['options']['response']['color']) ? $this->vars['options']['response']['color'] : '') ?>">

                    </div>
                    <div class="input-text">
                        <label for="class-color">Classe css à appliquer</label><!--
                        --><input name="class-color" type="text" value="<?= (!empty($this->vars['options']['response']['classColor']) ? $this->vars['options']['response']['classColor'] : '') ?>">

                    </div>

                    <?php
                    if (!empty($this->vars['options']['response']['id'])){ ?>
                        <input name="id" type="hidden" value="<?= $this->vars['options']['response']['id'] ?>">
                    <?php } ?>

                    <button class="form-btn-submit" type="submit">Valider</button>
                </form><!--
                <?php if (!empty($this->vars['options']['list'])) { ?>
                    --><div class="admin-content-widget">
                    <h3>ICI CONTENT LIST</h3>
                        <table>
                            <thead>
                                <td>
                                    Nom
                                </td>
                                <td>
                                    Classe CSS
                                </td>
                                <td>
                                    Action
                                </td>
                            </thead>
                            <tbody>
                            <?php foreach ($this->vars['options']['list'] as $key){ ?>
                                <tr>
                                    <td>
                                        <a href="/admin/handleColors/edit?id=<?= $key['id'] ?>" ><?= $key['color'] ?></a>
                                    </td>
                                    <td>
                                        <?= $key['classColor'] ?>
                                    </td>
                                    <td>
                                        <a href="/admin/handleColors/delete?id=<?= $key['id'] ?>" >Supprimer</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                <?php }else{ ?>
                    <div>
                        <p>Pas de liste d'élément pour le moment...</p>
                    </div>
                <?php } ?>

            </section>
        </main>
</body>
</html>
