<!DOCTYPE html>
<html lang="fr">
    <?php include("block__admin_head.phtml"); ?>

    <body>
        <?php include("block__admin_header.phtml"); ?>

        <main class="admin-wrapper flex">

            <?php include("block__admin_menu.phtml"); ?>
            <section class="admin-content">

                <h3>CONTENT INDEX</h3>
                <?php
                if (!empty($this->vars['options']['response']['id'])){ ?>
                    <input name="id" type="hidden" value="<?= $this->vars['options']['response']['id'] ?>">
                <?php } ?>
                <?php if (!empty($this->vars['options']['list'])) { ?>
                <div class="admin-content-widget">
                    <h3>CONTENT LIST : <?= ucfirst($this->vars['options']['labels']['displayName']) ?></h3>
                    <table>
                        <thead>
                        <?php
                        if (!empty($this->vars['options']['header'])) {
                            foreach ($this->vars['options']['header'] as $item) { ?>
                                <td>
                                    <?= str_replace('_', ' ', $item); ?>
                                </td>
                            <?php } ?>
                                <td>Action </td>
                        <?php } ?>
                        </thead>
                        <tbody>
                        <?php
                        if (!empty($this->vars['options']['list'])) {
                        foreach ($this->vars['options']['list'] as $item) { ?>
                            <tr>
                                <?php

                                foreach ($item as $key => $value) {
                                    if (in_array($key, $this->vars['options']['header'])) {
                                    // limit sting length for table display
                                    $value = strlen($value) > 20 ? substr($value, 0, 20) . '...' : $value;
                                    if (preg_match(\Services\FormBuilder\Core\FormHydrator::DATETIME_REGEX, $value)) {

                                        $date = \DateTime::createFromFormat('Y-m-d H:i:s', $value);
                                        $value = $date->format('d/m/Y');
                                    }
                                    if ($key === 'id') {

                                        $id = $value;
                                    }
                                    elseif($key === 'password'){
                                        $value = '********';
                                    }
                                    elseif($key === 'isSuperAdmin'){

                                        $class = boolval($value) ? 'admin_index__thin_col success' : 'admin_index__thin_col error';
                                        $value = boolval($value) ? '<i class="fas fa-thumbs-up"></i>': '<i class="fas fa-thumbs-down"></i>';

                                    }?>
                                    <td class="<?= ($key === 'isSuperAdmin') ?  $class : '' ?>">
                                        <a href="/content/form?id=<?= $id ?>&content_name=<?= $this->vars['options']['labels']['technicalName'] ?>&isEdit=true&content_type=<?= $this->vars['options']['content_name'] ?>&content_id=<?= $this->vars['options']['id'] ?>"><?= $value ?></a>
                                    </td>

                                <?php } }?>
                                <td class="admin_index__to_delete">
                                    <a href="/content/delete?id=<?= $id ?>&content_name=<?= $this->vars['options']['labels']['technicalName'] ?>">Supprimer</>
                                </td>
                            </tr>
                        <?php }
                        }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="admin_info__no_content">

                <?php } else{ ?>
                        <p>Pas de liste d'élément pour le moment...</p>

                <?php } ?>
                        <a href="/content/form?content_name=<?= $this->vars['options']['labels']['technicalName']?>&id=<?= $this->vars['options']['id']?>">Créer un <?= $this->vars['options']['name'] ?? 'contenu' ?></a>
                    </div>
            </section>

        </main>
        <script src="../../../public/bundle.js"></script>
</body>
</html>
