<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Portfolio</title>
        <link rel="stylesheet" href="/public/main.css">
    </head>
    <body>
        <header class="admin-header">
            <?php
            if (!empty($this->vars['options']['flash-message'])) { ?>
                <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
                    <?php
                    foreach ($this->vars['options']['flash-message'] as $key){ ?>
                        <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
                    <?php }
                    ?>
                </div>
            <?php } ?>
            <div class="header-content">
                <div class="header-welcome">
                    <h1>Technologie</h1>
                    <p>Ajouter une nouvelle technologie</p>
                </div>

                <div class="adminLogout">
                    <a href="/admin/login/logout" title="logout">DECONNEXION</a>
                    <a href="/" title="logout">Aller au sur le Front</a>
                </div>
            </div>
        </header>
        <main class="admin-wrapper flex">
            <aside class="admin-sidebar">
                <div>

                    <h2>Menu</h2>
                    <a href="/addContentElement">Ajouter un nouveau types de contenu</a>
                    <ul>
                        <li>
                            <a href="/admin/newProject">Ajouter un projet</a>
                        </li>
                        <li>
                            <a href="/admin/newTechnology">Ajouter une techno</a>
                        </li>
                        <li>
                            <a href="/admin/newLangage">Ajouter un Langage</a>
                        </li>
                        <li>
                            <a href="/admin/newCertification">Ajouter une certification</a>
                        </li>
                        <li>
                            <a href="/admin/newHobby">Ajouter un Hobby</a>
                        </li>
                        <li>
                            <a href="/admin/newOpquastRule">Ajouter une règle Opquast</a>
                        </li>
                        <li>
                            <a href="/admin/handleColors">Gérer les couleurs des étiquettes</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h2>API</h2>
                    <ul>
                        <li>
                            <a href="/admin/apiDoc">Documentation API</a>
                        </li>
                    </ul>
                </div>

            </aside>
            <section class="admin-content">
                <form class="admin-form" action="/admin/handleColors/handleContentData" method="post">

                    <h3>ICI LE NOM DU CONTENT</h3>
                    <div class="input-text">
                        <label for="color">Nom de la techno</label><!--
                        --><input name="color" type="text" value="<?= (!empty($this->vars['options']['response']['color']) ? $this->vars['options']['response']['color'] : '') ?>">

                    </div>
                    <div class="input-text">
                        <label for="class-color">Classe css à appliquer</label><!--
                        --><input name="class-color" type="text" value="<?= (!empty($this->vars['options']['response']['classColor']) ? $this->vars['options']['response']['classColor'] : '') ?>">

                    </div>

                    <?php
                    if (!empty($this->vars['options']['response']['id'])){ ?>
                        <input name="id" type="hidden" value="<?= $this->vars['options']['response']['id'] ?>">
                    <?php } ?>

                    <button class="form-btn-submit" type="submit">Valider</button>
                </form><!--
                <?php if (!empty($this->vars['options']['list'])) { ?>
                    --><div class="admin-content-widget">
                    <h3>ICI CONTENT LIST</h3>
                        <table>
                            <thead>
                                <td>
                                    Nom
                                </td>
                                <td>
                                    Classe CSS
                                </td>
                                <td>
                                    Action
                                </td>
                            </thead>
                            <tbody>
                            <?php foreach ($this->vars['options']['list'] as $key){ ?>
                                <tr>
                                    <td>
                                        <a href="/admin/handleColors/edit?id=<?= $key['id'] ?>" ><?= $key['color'] ?></a>
                                    </td>
                                    <td>
                                        <?= $key['classColor'] ?>
                                    </td>
                                    <td>
                                        <a href="/admin/handleColors/delete?id=<?= $key['id'] ?>" >Supprimer</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                <?php }else{ ?>
                    <div>
                        <p>Pas de liste d'élément pour le moment...</p>
                    </div>
                <?php } ?>

            </section>
        </main>
</body>
</html>