<!DOCTYPE html>
<html lang="fr">
    <?php include("block__admin_head.phtml"); ?>

    <body>
        <?php include("block__admin_header.phtml"); ?>

        <main class="admin-wrapper flex">

            <?php include("block__admin_menu.phtml"); ?>
            <section class="admin-content">

                <h3>CONTENT INDEX</h3>
                <?php
                if (!empty($this->vars['options']['response']['id'])){ ?>
                    <input name="id" type="hidden" value="<?= $this->vars['options']['response']['id'] ?>">
                <?php } ?>
                <?php if (!empty($this->vars['options']['list'])) { ?>
                <div class="admin-content-widget">
                    <h3>CONTENT LIST : <?= ucfirst($this->vars['options']['labels']['displayName']) ?></h3>
                    <table>
                        <thead>
                        <?php
                        if (!empty($this->vars['options']['header'])) {
                            foreach ($this->vars['options']['header'] as $item) { ?>
                                <td>
                                    <?= $item ?>
                                </td>
                                <?php
                            }
                        }
                        ?>
                        </thead>
                        <tbody>
                        <?php
                        if (!empty($this->vars['options']['list'])) {
                        foreach ($this->vars['options']['list'] as $item) { ?>
                            <tr>
                                <?php foreach ($item as $key => $value) {
                                    if ($key === 'id') {
                                        $id = $value;
                                    }
                                    elseif($key === 'password'){
                                        $value = '********';
                                    } ?>
                                    <td>
                                        <a href="/admin/content/formContent?id=<?= $id ?>&content_name=<?= $this->vars['options']['labels']['technicalName'] ?>&isEdit=true&content_type=<?= $this->vars['options']['content_name'] ?>&content_id=<?= $this->vars['options']['id'] ?>"><?= $value ?></a>
                                    </td>

                                <?php } ?>
                                <td>
                                    <a href="/admin/content/delete?id=<?= $id ?>&content_name=<?= $this->vars['options']['labels']['technicalName'] ?>">Supprimer</a>
                                </td>
                            </tr>
                        <?php }
                        }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div>

                <?php } else{ ?>
                        <p>Pas de liste d'élément pour le moment...</p>

                <?php } ?>
                        <a href="/admin/content/formContent?content_name=<?= $this->vars['options']['labels']['technicalName']?>&id=<?= $this->vars['options']['id']?>">Créer un <?= $this->vars['options']['name'] ?? 'contenu' ?></a>
                    </div>
            </section>

        </main>
</body>
</html>
