<!DOCTYPE html>
<html lang="fr">
<?php include("block__admin_head.phtml"); ?>

<body class="wrapper-installation">
<header>
<?php
if (!empty($this->vars['options']['flash-message'])) { ?>
    <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
        <p><?= $this->vars['options']['flash-message']['message'] ?></p>
    </div>
<?php } ?>
<h1>Installation du projet</h1>
</header>
<form class="installation-form" action="/installation" method="post">
    <fieldset>
        <legend>
            Compte Administrateur
        </legend>
        <div class="admin-form-field">
            <label for="email">Email</label>
            <input id="email" name="email" type="text" value="<?= (empty($_POST['email']) ? '' : $_POST['email']) ?>"
                   required/>

        </div>
        <div class="admin-form-field">
            <label for="login">Login</label>
            <input id="login" name="login" type="text" value="<?= (empty($_POST['login']) ? '' : $_POST['login']) ?>"
                   required/>
        </div>
        <div class="admin-form-field">
            <label for="pwd"">Mot de passe</label>
            <input id="pwd" name="pwd" type="password" value="<?= (empty($_POST['pwd']) ? '' : $_POST['pwd']) ?>"
                   required/>
        </div>
        <input type="hidden" name="isSuperAdmin" value="true">
    </fieldset>
    <fieldset>
        <legend>
            Informations base de données
        </legend>
        <div class="admin-form-field">
            <label for="db_name">Nom de la base de donnée</label>
            <input id="db_name" name="db_name" type="text" value="<?= (empty($_POST['name']) ? '' : $_POST['name']) ?>"
                   required/>
        </div>
        <div class="admin-form-field">
            <label for="db_host">Host</label>
            <input id="db_host" name="db_host" type="text" value="<?= (empty($_POST['host']) ? '' : $_POST['host']) ?>"
                   required/>
        </div>
        <div class="admin-form-field">
            <label for="db_admin">Admin</label>
            <input id="db_admin" name="db_admin" type="text"
                   value="<?= (empty($_POST['admin']) ? '' : $_POST['admin']) ?>" required/>
        </div>
        <div class="admin-form-field">
            <label for="db_password">Mot de passe</label>
            <input id="db_password" name="db_password" type="password"
                   value="<?= (empty($_POST['password']) ? '' : $_POST['password']) ?>"/>
        </div>
        <input type="hidden" name="private" value="true">
        <button class="form-btn-submit" type="submit">Installer</button>
    </fieldset>
</form>
<script src="../../../public/bundle.js"></script>
</body>
</html>
