<!DOCTYPE html>
<html lang="fr">
    <?php include("block__admin_header.phtml"); ?>

    <body>
            <?php include("block__admin_header.phtml.phtml"); ?>

            <main class="admin-wrapper flex">
                <?php include("block__admin_menu.phtml"); ?>
                <section class="admin-content">

                    <form action="/admin/newTechnology/saveNewCategory" method="post">

                        <label for="name">Nom de la techno</label>
                        <input id="name" type="text">

                        <label for="class-color">Couleur de l'étiquette</label>
                        <select name="class-color" id="class-color">
                            <option value="test">rouge</option>
                            <option value="test">bleu</option>
                            <option value="test">vert</option>
                            <option value="test">jaune</option>
                        </select>
                        <button type="submit">Valider</button>
                    </form>


                </section>
            </main>
    </body>
</html>
