<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Portfolio</title>
        <link rel="stylesheet" href="/public/main.css">
    </head>
    <body>
        <header class="admin-header">
            <?php
            if (!empty($this->vars['options']['flash-message'])) { ?>
                <div class="flash-message <?= $this->vars['options']['flash-message']['type-class'] ?>">
                    <?php
                    foreach ($this->vars['options']['flash-message'] as $key){ ?>
                        <p class="flash-message <?= $key['type-class'] ?>"><?= $key['message'] ?></p>
                    <?php }
                    ?>
                </div>
            <?php } ?>
            <div class="header-content">
                <div class="header-welcome">
                    <h1>Technologie</h1>
                    <p>Ajouter une nouvelle technologie</p>
                </div>

                <div class="adminLogout">
                    <a href="/admin/login/logout" title="logout">DECONNEXION</a>
                </div>
            </div>
        </header>
        <main class="admin-wrapper flex">
            <aside class="admin-sidebar">
                <div>
                    <h2>Menu</h2>
                    <ul>
                        <li>
                            <a href="/admin/newProject">Ajouter un projet</a>
                        </li>
                        <li>
                            <a href="/admin/newTechnology">Ajouter une techno</a>
                        </li>
                        <li>
                            <a href="/admin/newLangage">Ajouter un Langage</a>
                        </li>
                        <li>
                            <a href="/admin/newCertification">Ajouter une certification</a>
                        </li>
                        <li>
                            <a href="/admin/newHobby">Ajouter un Hobby</a>
                        </li>
                        <li>
                            <a href="/admin/newOpquastRule">Ajouter une règle Opquast</a>
                        </li>
                        <li>
                            <a href="/admin/handleColors">Gérer les couleurs des étiquettes</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h2>API</h2>
                    <ul>
                        <li>
                            <a href="/admin/apiDoc">Documentation API</a>
                        </li>
                    </ul>
                </div>

            </aside>
            <section class="admin-content">

                <form action="/admin/newTechnology/saveNewCategory" method="post">

                    <label for="name">Nom de la techno</label>
                    <input id="name" type="text">

                    <label for="class-color">Couleur de l'étiquette</label>
                    <select name="class-color" id="class-color">
                        <option value="test">rouge</option>
                        <option value="test">bleu</option>
                        <option value="test">vert</option>
                        <option value="test">jaune</option>
                    </select>
                    <button type="submit">Valider</button>
                </form>


            </section>
        </main>
</body>
</html>